name: pytest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Install Python dependencies
      run: |
        pip install -r .github/workflows/requirements.txt
        
    - name: Run test suite
        run: |
          pytest tests/test.py
