name: Update Sphinx documentation
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  sphinx:
    name: Sphinx ${{ matrix.sphinx-version }}

    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            python-version: "3.6"
            sphinx-version: "1.6.7"
            nbsphinx-version: "0.8.8"

    runs-on: ${{ matrix.os }}
            
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install sphinx==${{ matrix.sphinx-version }}
           pip install nbsphinx==${{ matrix.nbsphinx-version }}
    
      - name: Build sphinx documentation
        run: |
           docs/make html
