name: Update Sphinx docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_sphinx:
    name: Build Sphinx documentation

    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            python-version: "3.6.9"
            sphinx-version: "1.6.7"
            nbsphinx-version: "0.8.8"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Sphinx
        run: pip install sphinx==${{ matrix.sphinx-version }}

      - name: Install Sphinx support for notebooks
        run: pip install nbsphinx==${{ matrix.nbsphinx-version }}

      - name: Build Sphinx documentation
        run: docs/make html
