name: Update Sphinx documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sphinx:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx=="1.6.7"
          pip install nbsphinx=="0.8.8"

      - name: Build sphinx documentation
        run: |
          docs/make html

