name: Update Sphinx documentation
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  sphinx:
    #name: Sphinx "1.6.7"

    # Using matrix just to get variables which are not environmental variables
    # # and also to sync with other workflows which use matrix.
    # strategy:
    #   matrix:
    #     include:
    #       - os: ubuntu-18.04
    #         python-version: "3.6"
    #         sphinx-version: "1.6.7"
    #         nbsphinx-version: "0.8.8"

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install sphinx=="1.6.7"
          pip install nbsphinx=="0.8.8"

      - name: Build Sphinx documentation
        run: |
          docs/make html
